# Generated by Django 4.2.7 on 2023-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
