# Generated by Django 4.2.7 on 2023-11-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('SUBIDO', 'subido'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='SUBIDO', max_length=20),
        ),
    ]
