# Generated by Django 4.2.7 on 2023-11-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_documento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
